name: Notify Commit

on:
  push:
    branches:
      - master

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_COMMIT: ${{ github.sha }}
          GITHUB_REPO: ${{ github.repository }}
        run: |
          curl -H "Content-Type: application/json" \
            -X POST \
            -d "{
              \"embeds\": [
                {
                  \"title\": \"New commit pushed to ${GITHUB_REPO}\",
                  \"description\": \"**Author:** ${GITHUB_ACTOR}\n[View on Github](https://github.com/${GITHUB_REPO}/commit/${GITHUB_COMMIT})\",
                  \"color\": 43775
                }
              ]
            }" \
            $DISCORD_WEBHOOK
